### PR TITLE
Added bash install script.

### PR DESCRIPTION
**Pull request by tjmckinley**

### CODE REVIEW

**Comment by fentonscode** [comment]
Can we confirm that **all** the deleted vingettes are in the other repository? And there is no changes to content?

**Comment by tjmckinley** [comment]
Ah, it seems that the quantile kriging one is different, but I suspect this is because of line endings rather than content, but can't check that because the git diff says every line is different. It seems that Danny has put the Rmd of his adventures into this repo, but the HTML into the other repo. A couple of them don't exist.

Could we port the whole folder over to the other repo so we're not deleting anything, and then ask people to check accordingly?

**Comment by tjmckinley** [comment]
I've just realised that the PR automatically includes all changes in the branch. I had opened the PR with just the script update, but then when I pushed the removal of the vignettes it added that to the PR. Interesting! I'll add a PR to uq4covid.github.io to pass the vignettes into that repo instead.

**Comment by fentonscode** [comment]
I merged a bit soon it appears, however because this is github they are recoverable if users want to get them from older commits

**Comment by tjmckinley** [comment]
Yeah, sorry, that was my bad, I didn't realise that it got automatically added to the PR. However, I've recovered them easily enough and added a PR to move them to the other repo, with an e-mail request to the authors to move them into the correct folder with the latest version.

**Pull request merged**
